name: CI/CD Simulation - Diet Analysis App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build & Test Dockerized App
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Installs dependencies
      - name: Install dependencies
        run: |
          pip install pandas matplotlib seaborn azure-storage-blob

      # Runs lint or basic test
      - name: Run Python syntax check
        run: |
          python -m py_compile data_analysis.py
          python -m py_compile lambda_function.py

      # Build The Docker image
      - name: Build Docker image
        run: |
          docker build -t diet-analysis .

      # Runs a Docker container for verification
      - name: Run Docker container simulation
        run: |
          docker run --rm diet-analysis

  push-to-dockerhub:
    name: Push Image to Docker Hub
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and tag image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/diet-analysis:latest .

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diet-analysis:latest
